version: '3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile-application-tests
    command: ./gradlew --no-daemon test
    environment:
      BROWSER_HOST: "browser"
      BROWSER_PORT: "4444"
    links:
      - browser
  browser:
    image: selenium/standalone-firefox-debug:latest
    ports:
      - "4444:4444"
      - "5900:5900"

